---
title: "Superenhancer and there Influence on Expression"
output: html_notebook
---

reading in data or defining a reading in function
```{r}
library(readr)
library(biomaRt)
library(stringr)
library(ggplot2)

sleuth_results <- read_csv("data/sleuth.results.WT.gene_log2FC.csv") # Differential Gene Expression Table, can be requested (version 20200420)


readingInFunction <- function(path){
  
  geneList <- read_delim(path, ";", escape_double = FALSE, trim_ws = TRUE)
  geneList <- geneList$ext_gene
  
  sleuth_results <- sleuth_results[sleuth_results$ext_gene %in% geneList, ]
  
  if (TRUE) {
    #Annotate Gene Name to Diff exp Table
    #sleuth_results$ID <- runif(length(sleuth_results$ens_gene ), 0.0, 1.0)
    
    ##############BioMart annotation#######################
    
    ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl"
   # ,host="jan2019.archive.ensembl.org"
    )
    #listDatasets(ensembl)
    attributes = listAttributes(ensembl)
    #attributes[1:100,]
    filters = listFilters(ensembl)
    #filters[1:100,]
    
    N <- data.frame(getBM(attributes=c("ensembl_gene_id_version","external_gene_name"),
       	       filters=c('external_gene_name'),
               values = sleuth_results$ext_gene ,
               mart=ensembl))
    
    sleuth_results_anno <- merge(N,sleuth_results, by.x= "external_gene_name", by.y= "ext_gene")
  }
  return(sleuth_results_anno)
}
```



prepping data

Reading in Data of SE overlapping with each other/ or not, generated by NGSstrang (can be requested)
```{r}
parentPath <- "data/RawDataFromManuela"

SE_PC_TPM <- readingInFunction(file.path(parentPath,"SE_PCspecific_Maerz2020.csv"))[,c("external_gene_name","b","se_b") ]
names(SE_PC_TPM)[names(SE_PC_TPM) == 'external_gene_name'] <- 'ext_gene'

SE_HC_TPM <- readingInFunction(file.path(parentPath,"SE_HCspecific_3_2020TPM.csv"))[,c("external_gene_name","b","se_b") ]
names(SE_HC_TPM)[names(SE_HC_TPM) == 'external_gene_name'] <- 'ext_gene'

SE_COM_TPM <- readingInFunction(file.path(parentPath,"SE_Common_3_2020.csv"))[,c("external_gene_name","b","se_b") ]
names(SE_COM_TPM)[names(SE_COM_TPM) == 'external_gene_name'] <- 'ext_gene'

# subsample to be specfic
SE_COM_TPM <- SE_COM_TPM[!(SE_COM_TPM$ext_gene %in% SE_HC_TPM$ext_gene)|!(SE_COM_TPM$ext_gene %in% SE_PC_TPM$ext_gene),]
SE_PC_TPM <- SE_PC_TPM[!(SE_PC_TPM$ext_gene %in% SE_HC_TPM$ext_gene) ,]
SE_HC_TPM <- SE_HC_TPM[!(SE_HC_TPM$ext_gene %in% SE_PC_TPM$ext_gene) ,]




mergingTables <- function(signalDF, backgroundDF){
    signalDF <- signalDF[,c("ext_gene","b")]
    backgroundDF <- backgroundDF[,c("ext_gene","b")]
    
    tmpBG <- backgroundDF[!(backgroundDF$ext_gene %in% signalDF$ext_gene), ]
    tmpBG$enh <- 0
    signalDF$enh <- 1
    
    tmpReturn <- rbind(tmpBG, signalDF)
    
    tmpReturn$enh <- as.factor(tmpReturn$enh)
    tmpReturn <- tmpReturn[ !(is.na(tmpReturn$ext_gene)) , ]
    return(unique(tmpReturn))
}

SE_PC_merge <- mergingTables(SE_PC_TPM,sleuth_results )
SE_HC_merge <- mergingTables(SE_HC_TPM,sleuth_results )
SE_Com_merge <- mergingTables(SE_COM_TPM,sleuth_results )
```

function for the brms model and a plot for the PPC
```{r}
library(brms)
library("bayesplot")
library(ggplot2)

baysCall_t <- function(mergedDF){
  uneq_var_frm <- bf(b ~ enh, sigma ~ enh)
    mod_uneqvar <- brm(
    uneq_var_frm, 
    data = mergedDF, 
    cores=4 ,
    family = "student"
  )
    return(mod_uneqvar)
}

PPCPlot <- function(modleBRMS, brmsInput,PlotTile){
  yrep<- posterior_predict(modleBRMS, draws = 500)
  p <- ppc_dens_overlay(brmsInput$b[brmsInput$enh == 0], yrep[1:100, brmsInput$enh == 0])
  preal <- ppc_dens_overlay(brmsInput$b[brmsInput$enh == 1], yrep[1:100, brmsInput$enh == 1])
  
    p <- p + ggtitle(PlotTile) +xlab("") +xlim(-4,4) +ylim(0,0.8) +theme_linedraw()+theme(legend.position = "none",axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
      annotate("text",  x=Inf, y = Inf, label = "no SE", vjust=2, hjust=2)
    
  preal <- preal + ggtitle("") +xlab("beta value") +xlim(-4,4) +ylim(0,0.8) +
    theme_linedraw()+
    theme(legend.position = "none",plot.title=element_blank())+
    annotate("text",  x=Inf, y = Inf, label = "SE", vjust=2, hjust=2)
  

  
  return(plot_grid(p,preal, nrow = 2))
}



```

Model
```{r}
PC_t <- baysCall_t(SE_PC_merge)
HC_t <- baysCall_t(SE_HC_merge)
Com_t <- baysCall_t(SE_Com_merge)
```


PPC
```{r}
library(gridExtra)
plotHC_t <- PPCPlot(HC_t,SE_HC_merge,"PPC of HC-specifc SE")
plotPC_t <- PPCPlot(PC_t,SE_PC_merge,"PPC of PC-specifc SE")
plotCom_t <- PPCPlot(Com_t,SE_Com_merge,"PPC of common SE")


pc <- grid.arrange(plotPC_t,plotHC_t,plotCom_t)
#ggsave("output/modle/PPC_summary_20200430_Specfic.tiff", plot=pc, height = 9, width = 8)
```

save date
```{r}
save(plotHC_t,file= file.path("ZS/modle/PPCHC_t_20200325_specific.ggplot"))
save(plotPC_t,file= file.path("ZS/modle/PPCPC_t_20200325_specific.ggplot"))
save(plotCom_t, file=file.path("ZS/modle/PPCCom_t_20200325_specific.ggplot"))
x <- list(HC_t,SE_HC_merge)
save(x, file=file.path("ZS/modle/modleInOutHC_t_20200325_specific.Rmd"))
x <- list(PC_t,SE_PC_merge)
save(x, file=file.path("ZS/modle/modleInOutPC_t_20200325_specific.Rmd"))
x <- list(Com_t,SE_Com_merge)
save(x, file=file.path("ZS/modle/modleInOutCom_t_20200325_specific.Rmd"))
rm(x)
```

loading in the data again
```{r}
#HC_t <- get(load("ZS/modle/modleInOutHC_t_20200325_specific.Rmd"))[[1]]

#PC_t <- get(load("ZS/modle/modleInOutPC_t_20200325_specific.Rmd"))[[1]]

#Com_t <- get(load("ZS/modle/modleInOutCom_t_20200325_specific.Rmd"))[[1]]
```


effectsize Plot
```{r}
HC <- data.frame(b_enh1= posterior_samples(HC_t)[,"b_enh1"], enh = "HC")
PC <- data.frame(b_enh1=posterior_samples(PC_t)[,"b_enh1"], enh = "PC")
Com <- data.frame(b_enh1 =posterior_samples(Com_t)[,"b_enh1"], enh = "Com")

m <- rbind(PC,HC)
m <- rbind(m,Com)

ggplot(m, aes(x=b_enh1, color = enh)) +
  geom_density() +
  theme_linedraw() +
  scale_color_manual(values = c("#ffa500","#4682B4","gray")) +
  geom_vline(xintercept = 0, color="white", lty=2, lwd=1.2) +
  ggtitle("Effect Size") +
  guides(color=guide_legend(title="enhancer")) +
  xlim(-0.45,0.45)+
  xlab("slope") +
  ylab("")


#ggsave("output/modle/EffektSize_t_20200430_specific.tiff", height = 4, width = 7)
getwd()
```
